version: '3'

services:
    synapse:
        image: matrixdotorg/synapse
        restart: unless-stopped
        env_file:
            - synapse.env
        environment:
            - SYNAPSE_REPORT_STATS=no
            - SYNAPSE_ENABLE_REGISTRATION=no
            - SYNAPSE_ALLOW_GUEST=no
            - SYNAPSE_LOG_LEVEL=WARN
            #- SYNAPSE_LOG_LEVEL=DEBUG
            - SYNAPSE_NO_TLS=yes
        volumes:
            - ./synapse/data:/data
            - ./registrations/facebook-registration.yaml:/data/appservices/facebook-registration.yaml
            - ./registrations/slack-registration.yaml:/data/appservices/slack-registration.yaml
            - ./registrations/telegram-registration.yaml:/data/appservices/telegram-registration.yaml
        ports:
            - 8008:8008/tcp
    matrix-puppet-facebook:
        image: matrix-puppet-facebook
        restart: unless-stopped
        environment:
            - DEBUG=*matrix-puppet*
        volumes:
            - ./matrix-puppet-facebook/config.json:/opt/matrix-puppet-facebook/config.json
            - ./matrix-puppet-facebook/appstate.json:/opt/matrix-puppet-facebook/appstate.json
            - ./registrations/facebook-registration.yaml:/opt/matrix-puppet-facebook/facebook-registration.yaml
    matrix-puppet-slack:
        image: matrix-puppet-slack
        restart: unless-stopped
        environment:
            - DEBUG=*matrix-puppet*
        volumes:
            - ./matrix-puppet-slack/config.json:/opt/matrix-puppet-slack/config.json
            - ./registrations/slack-registration.yaml:/opt/matrix-puppet-slack/slack-registration.yaml
    mautrix-telegram:
        image: tulir/mautrix-telegram
        restart: unless-stopped
        volumes:
            - ./mautrix-telegram:/data
            - ./registrations/telegram-registration.yaml:/data/registration.yaml
